# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'de2fe980-db59-4619-a682-2db9c03fbbf0'
  containerRegistry: 'customonprem.azurecr.io'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:

- stage: DotnetBuildAndTest
  displayName: Build dotnet libraries or executable and run tests.
  jobs:
  - job: BuildDotnetAndTest
    displayName: Job to dotnet build and dotnet test.
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet build the common library
      inputs:
        command: 'build'
        projects: 'common'
    - task: DotNetCoreCLI@2
      displayName: dotnet build the server app
      inputs:
        command: 'build'
        projects: 'host'
    - task: DotNetCoreCLI@2
      displayName: dotnet build the test client app
      inputs:
        command: 'build'
        projects: 'client'
    - task: DotNetCoreCLI@2
      displayName: dotnet test the unit tests
      inputs:
        command: 'test'
        projects: 'tests'

- stage: BuildDockerContainersAndPush
  displayName: Build and push containers stage
  jobs:  
  - job: BuildContainersAndPush
    displayName: Job to build and push the server and test client containers.
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build server image
      inputs:
        command: build
        repository: genesys/mcp/server
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile_server'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: Build client image
      inputs:
        command: build
        repository: genesys/mcp/client
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile_client'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: Push server image to container registry
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        repository: genesys/mcp/server
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: Push client image to container registry
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        repository: genesys/mcp/client
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

    # josh test task
    - task: Docker@2
      displayName: Push client image to container registry
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        script: |
          docker pull joshcacr.azurecr.io/test_repo:latest 